### ISSUE TITLE
defusedxml lacks an Element class

### ISSUE THREAD

**Issue by JonZeolla** [tiran/defusedxml#48]
`defusedxml` currently lacks an Element class.  In order to implement return types on functions that return an [`Element`](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element), currently you need to leverage `xml.etree.ElementTree.Element`, which then causes issues when using the [discovery feature](https://github.com/python/cpython/blob/91874bb07161bb481b6f5ea18ffafe69cb8cac30/Lib/unittest/loader.py#L325) of `unittest`.

Here is an example error message that `unittest` can show when mixing `xml.etree.ElementTree` and `defusedxml`.
```
======================================================================
FAIL: test_parse_xml (XYZ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonzeolla/src/abc/tests/test_api_functions.py", line 155, in test_parse_xml
    self.assertIs(
AssertionError: <class 'xml.etree.ElementTree.Element'> is not <class 'xml.etree.ElementTree.Element'>

----------------------------------------------------------------------
```

**Comment by brunato** [comment]
This maybe related to #40.

**Comment by brunato** [comment]
More about PR #40 proposed fix. 

Internal import of xml.etree.ElementTree in *defusedxml* with Python 3 loads the pure Python version of ElementTree instead of the C optimized module. This happens if the xml.etree.ElementTree is not already loaded in *sys.modules*. 

That could be related to this issue. You can test putting an `import xml.etree.ElementTree` at the start of your test scripts, to check if the test still fails.

**Comment by remram44** [comment]
This also breaks `xlrd` which imports `defusedxml.cElementTree as ET` and checks for `ET.ElementTree.iter` which works with the real `xml.etree.cElementTree` but there's no `ElementTree` in `defusedxml.cElementTree`. Therefore it reverts to using `getiterator()` instead of `iter()`.

`xlrd` is no longer maintained and this is probably what will break first.

**Comment by xmo-odoo** [comment]
@remram44 well guessed, xlrd's xlsx support is broken in 3.9, because as you say it checks against ET.ElementTree, which doesn't exist if ET = defusedxml.ElementTree, so falls back on getiterator() which was removed from 3.9

**Comment by fiendish** [comment]
> @remram44 well guessed, xlrd's xlsx support is broken in 3.9, because as you say it checks against ET.ElementTree, which doesn't exist if ET = defusedxml.ElementTree, so falls back on getiterator() which was removed from 3.9

XLRD was fixed and now supports python 3.9.

**Comment by xmo-odoo** [comment]
@fiendish 
> The maintainer was cajoled out of retirement, and xlrd was fixed to support python 3.9 in December.

Nice, that would be the 2.0 release then?

**Comment by fiendish** [comment]
> @fiendish
> 
> > The maintainer was cajoled out of retirement, and xlrd was fixed to support python 3.9 in December.
> 
> Nice, that would be the 2.0 release then?

Yes, see https://github.com/python-excel/xlrd/blob/master/CHANGELOG.rst#200-11-december-2020
The trade is that it drops support for xlsx files and exists now only for xls.

**Comment by nikhiljohn10** [comment]
No sure if this is the right place to ask this. Since there is no typing specified, everything return Unknown type for me in defusedxml. So I made this sample code. I want to know if this is a bad workaround for fixing typing until permanent fix is release?

```python
from typing import Dict
from defusedxml import ElementTree as ET

class Element:
    tag: str
    attrib: Dict[str, str]
    text: str
    tail: str

    def find(self, path: str, namespaces: Dict[str, str] = None) -> 'Element': ...
    def append(self, subelement: 'Element') -> None: ...
    def remove(self, subelement: 'Element') -> None: ...
    
    # So on ...

class ElementTree(ET):
    def getroot(self) -> Element: ... 
    
    # So on ...

tree: ElementTree = ET.parse("./input.xml")
root: Element = tree.getroot()
root.tag = 'Home'
root.attrib = { 'color': 'red' }
print(ET.tostring(
    root,
    encoding="unicode",
    xml_declaration=True
).decode("utf8"))
```

**Comment by nngo** [comment]
I am also encountering this AttributeError issue for `Element` trying to switch from `xml.etree.ElementTree` to `defusedxml.ElementTree`
```
AttributeError: module 'defusedxml.ElementTree' has no attribute 'Element'
```
Are there any workarounds for this? additionally, I code that uses `ElementTree.SubElement` so that will probably also not work with `defusedxml` as of version 0.7.1.

**Comment by mraspaud** [comment]
Just got hit by this one too, any update on this?

**Comment by yukihiko-shinoda** [comment]
If it can be accepted to use `xml.etree.ElementTree` only for type checking, following micro temporary solution may be help:

```python
from defusedxml import ElementTree

if TYPE_CHECKING:
    from xml.etree.ElementTree import Element  # nosec B405

def create_element(xml: str) -> "Element":
    return ElementTree.fromstring(xml, forbid_dtd=True)  # type: ignore[no-any-return]
```

This can avoid to import `xml.etree.ElementTree` atleast in production.

**Comment by lokucrazy** [comment]
hi has there been any updates on this?  I'm using the above fix by @yukihiko-shinoda but I would prefer to be able to import Element fro defusedxml

**Comment by tiran** [comment]
defusedxml only provides functions and classes related to loading and parsing of XML. For everything else, use the corresponding functions, classes, and constants from Python's stdlib.

See https://pypi.org/project/defusedxml/0.8.0rc1/#defusedxml

> The defusedxml modules are not drop-in replacements of their stdlib counterparts. The modules only provide functions and classes related to parsing and loading of XML. For all other features, use the classes, functions, and constants from the stdlib modules.

```
>>> from xml.etree import ElementTree as ET
>>> from defusedxml import ElementTree as DET
>>> root = DET.fromstring("<root/>")
>>> root.append(ET.Element("element"))
>>> ET.tostring(root)
b'<root><element /></root>'
```
